export type SpecialtyTemplate = {
    restrictions: string;
    differentials: string;
    emergency_rules: string;
    return_policy: string;
    insurance_policy: string;
    common_procedures: string;
    consultation_duration: string;
    pre_consultation_prep: string;
};

export const SPECIALTY_CATEGORIES = [
    { id: "clinica_geral", label: "Clínica Geral / Família", icon: "🩺", description: "Clínico Geral, Médico de Família" },
    { id: "pediatria", label: "Pediatria", icon: "👶", description: "Pediatra, Neonatologista" },
    { id: "ginecologia", label: "Ginecologia e Obstetrícia", icon: "🌸", description: "Ginecologista, Obstetra" },
    { id: "cardiologia", label: "Cardiologia", icon: "❤️", description: "Cardiologista" },
    { id: "ortopedia", label: "Ortopedia e Traumatologia", icon: "🦴", description: "Ortopedista, Traumatologista" },
    { id: "oftalmologia", label: "Oftalmologia", icon: "👁️", description: "Oftalmologista" },
    { id: "dermatologia", label: "Dermatologia e Estética", icon: "✨", description: "Dermatologista, Medicina Estética" },
    { id: "psiquiatria", label: "Psiquiatria e Saúde Mental", icon: "🧠", description: "Psiquiatra" },
    { id: "psicologia", label: "Psicologia", icon: "💬", description: "Psicólogo (CRP)" },
    { id: "odontologia", label: "Odontologia", icon: "🦷", description: "Dentista, Ortodontista, Implantodontista" },
    { id: "endocrinologia", label: "Endocrinologia e Nutrologia", icon: "🔬", description: "Endocrinologista, Nutrólogo" },
    { id: "otorrino", label: "Otorrinolaringologia", icon: "👂", description: "Otorrino" },
    { id: "urologia", label: "Urologia", icon: "🔵", description: "Urologista" },
    { id: "gastroenterologia", label: "Gastroenterologia", icon: "🫁", description: "Gastroenterologista" },
    { id: "nutricao_fisio", label: "Nutrição ou Fisioterapia", icon: "🥗", description: "Nutricionista, Fisioterapeuta" },
    { id: "outros", label: "Outra Especialidade", icon: "⚕️", description: "Qualquer outra especialidade" },
];

export const SPECIALTY_TEMPLATES: Record<string, SpecialtyTemplate> = {
    clinica_geral: {
        restrictions: "Não realizamos cirurgias complexas ou procedimentos estéticos avançados. Casos gravíssimos são encaminhados a especialistas ou PA.",
        differentials: "Atendimento humano, foco na saúde integral, e acompanhamento próximo de longo prazo.",
        emergency_rules: "Se o paciente relatar dor torácica aguda, falta de ar severa ou perda de consciência, oriente buscar um Pronto-Socorro ou SAMU (192) imediatamente.",
        return_policy: "Retorno gratuito em até 15 dias após a consulta de avaliação para mostrar exames.",
        insurance_policy: "Atendemos os convênios listados. Para os demais, emitimos nota para reembolso.",
        common_procedures: "Check-up clínico, avaliação geral, renovação de receitas, tratamento de infecções agudas.",
        consultation_duration: "30-45 minutos",
        pre_consultation_prep: "Traga exames anteriores e lista de medicamentos em uso, se aplicável.",
    },
    pediatria: {
        restrictions: "Não atendemos adultos. Procedimentos cirúrgicos só são feitos se expressamente agendados.",
        differentials: "Ambiente lúdico preparado para crianças, atendimento com muito carinho e paciência.",
        emergency_rules: "Febre muito alta em bebês pequenos, dificuldade respiratória profunda ou convulsões em crinaças: orientar ir ao pronto-socorro infantil imediatamente.",
        return_policy: "Retorno gratuito em até 15 dias para mostrar exames.",
        insurance_policy: "Verifique nossa lista de convênios.",
        common_procedures: "Puericultura (acompanhamento mensal), tratamento agudo de infecções, orientação vacinal e nutricional.",
        consultation_duration: "45-60 minutos",
        pre_consultation_prep: "Carteira de vacinação, curva de crescimento e exames anteriores.",
    },
    ginecologia: {
        restrictions: "Não realizamos consultas de pediatria geral. (Para obstetrícia: Não fazemos partos fora de ambiente hospitalar).",
        differentials: "Cuidado acolhedor e seguro, foco na saúde total da mulher.",
        emergency_rules: "Sangramento grave na gestação ou dor pélvica muito aguda repentina: encaminhar ao pronto-socorro de obstetrícia/ginecologia.",
        return_policy: "Retorno em até 15 dias.",
        insurance_policy: "Aceitamos os convênios listados para consultas.",
        common_procedures: "Preventivo (Papanicolau), inserção de DIU/Implanon, acompanhamento de menopausa, pré-natal.",
        consultation_duration: "40-60 minutos",
        pre_consultation_prep: "Não é necessário jejum (salvo indicação). Evite cremes vaginais 48h antes da coleta de Papanicolau.",
    },
    cardiologia: {
        restrictions: "Não realizamos cirurgias cardíacas na clínica, apenas em hospitais parceiros.",
        differentials: "Exames cardiológicos integrados no mesmo dia, médicos titulados pela SBC.",
        emergency_rules: "DOR NO PEITO tipo aperto irradiando para braço ou mandíbula, acompanhada de falta de ar profunda: RISCO DE INFARTO. LIGUE 192 (SAMU) AGORA ou vá à emergência urgência.",
        return_policy: "Retorno em 15-30 dias dependendo do exame solicitado.",
        insurance_policy: "Trabalhamos com recibos para reembolso para planos não listados.",
        common_procedures: "Consulta Cardiológica, Risco Cirúrgico, Eletrocardiograma (ECG), MAPA, Holter, Ecocardiograma.",
        consultation_duration: "30-45 minutos",
        pre_consultation_prep: "Traga sempre o último eletrocardiograma e exames de sangue recentes, e a sua receita com as doses exatas de medicações do coração.",
    },
    ortopedia: {
        restrictions: "Não tratamos problemas de outras especialidades ou estética. Cirurgias são programadas e feitas apenas em ambiente hospitalar.",
        differentials: "Resolvemos a dor do paciente. Especialistas focados por região (joelho, ombro, coluna).",
        emergency_rules: "Fraturas expostas, traumas de altíssima energia ou incapacidade súbita de andar: Ir para a emergência de Ortopedia imediatamente.",
        return_policy: "15 dias para retorno com exames.",
        insurance_policy: "Para procedimentos maiores (infiltrações, etc), consultar aprovação com convênio.",
        common_procedures: "Avaliação ortopédica, infiltração articular, terapia por ondas de choque, solicitação de ressonâncias.",
        consultation_duration: "20-40 minutos",
        pre_consultation_prep: "Se tiver, trazer ressonâncias, tomografias ou raios-x anteriores da área dolorida.",
    },
    oftalmologia: {
        restrictions: "Não fazemos transplantes de córnea ou cirurgias na clínica (somente no centro cirúrgico).",
        differentials: "Tecnologia de ponta para exames complexos, centro de diagnósticos próprio.",
        emergency_rules: "Baixa repentina da visão (cegueira súbita) ou dor extrema e vermelhidão no olho: requer avaliação Imediata de emergência (Pronto-Socorro oftalmológico).",
        return_policy: "Retorno em até 30 dias se solicitado óculos.",
        insurance_policy: "Verifique a lista de convênios.",
        common_procedures: "Consulta de rotina, prescrição de óculos, mapeamento de retina, tonometria (pressão do olho), indicação de cirurgia de catarata/refrativa.",
        consultation_duration: "20-30 minutos",
        pre_consultation_prep: "Atenção: A consulta rotineira pode necessitar dr dilatação das pupilas. O paciente não deve vir dirigindo caso precise usar colírio para dilatar e recomendamos trazer óculos de sol.",
    },
    dermatologia: {
        restrictions: "Não realizamos cirurgias plásticas. Nossos procedimentos são estéticos e clínicos não-invasivos ou minimamente invasivos.",
        differentials: "Aparelhos de laser de última geração, ambiente spa-like, foco em beleza natural e rejuvenescimento elegante.",
        emergency_rules: "Reação alérgica forte (inchaço em lábios/glote), falta de ar grave pós-procedimento: orientar ida imediata ao P.S. Mais próximo.",
        return_policy: "Retorno clínico em 15 dias. Retorno de Botox costuma ser de 15 a 21 dias.",
        insurance_policy: "Para parte ESTÉTICA (botox, preenchimentos, lasers, peelings), o atendimento é estritamente PARTICULAR. Convênios cobrem apenas consulta clínica de doenças da pele.",
        common_procedures: "Aplicação de Toxina Botulínica (Botox), Preenchimento com Ácido Hialurônico, Fios de Sustentação, Bioestimuladores (Sculptra/Radiesse), Lasers fracionados, Ultraformer/Ultra-som.",
        consultation_duration: "30-60 minutos",
        pre_consultation_prep: "Para avaliações do rosto, preferencialmente venha sem maquiagem ou base para avaliação adequada da pele.",
    },
    psiquiatria: {
        restrictions: "Não realizamos psicoterapia extensa (a não ser que especificado). Foco no diagnóstico e tratamento médico/fármaco.",
        differentials: "Sigilo total, empatia, escuta ativa e abordagem livre de estigmas e preconceitos.",
        emergency_rules: "Pensamentos concretos de autolesão, ideação suicida imediata grave ou surto psicótico agudo com agitação extrema: Ligar para emergência ou CVV (188) imediatamente.",
        return_policy: "Geralmente reavaliação médica padrão não é um 'retorno grátis', mas uma nova consulta.",
        insurance_policy: "Trabalhamos com recibo para reembolso. (Se aceitar convênio, listaremos os mesmos).",
        common_procedures: "Avaliação clínica, manejo farmacológico, renovação de receitas azuis/amarelas, diagnóstico de ansiedade/depressão/TDAH/Burnout.",
        consultation_duration: "45-60 minutos",
        pre_consultation_prep: "Relatórios de psicólogos ou antigos psiquiatras são muito úteis. Trazer receitas em uso atual.",
    },
    psicologia: {
        restrictions: "Por lei, psicólogos NÃO prescrevem nenhum tipo de medicamento. Apenas médicos (psiquiatras) fazem isso.",
        differentials: "Acolhimento profundo humano, ambiente seguro, confidencialidade total.",
        emergency_rules: "Urgências e surtos graves: ligar para o CVV 188 ou rede de urgência de saúde mental. Psicólogo não é socorrista 24hrs.",
        return_policy: "Na psicologia trabalhamos com 'Sessões' regulares rotineiras. Não há 'retorno' no conceito médico tradicional.",
        insurance_policy: "Geralmente trabalhamos apenas com atendimentos Particulares (podendo emitir recibo para reembolso de convênios).",
        common_procedures: "Psicoterapia individual, Avaliação psicológica, Psicoterapia de casal, Orientação Vocacional.",
        consultation_duration: "50 minutos (padrão da sessão)",
        pre_consultation_prep: "Basta estar num ambiente tranquilo se a sessão for online. Sem preparos adicionais.",
    },
    odontologia: {
        restrictions: "Não fazemos preenchimentos full face (reservado para plástica cirurgiões) ou cirurgias oncológicas.",
        differentials: "Odontologia sem dor (sedação consciente/óxido nitroso), especialistas, scanner digital 3D.",
        emergency_rules: "Sangramento que não para após uma extração ou inchaço extremo do rosto acompanhado de febre (abscesso agudo): procurar emergência.",
        return_policy: "Consultar especificações conforme o tipo de procedimento.",
        insurance_policy: "Muitos convênios cobrem restaurações, profilaxia e diagnóstico. Procedimentos como Facetas e Lentes de Contato de Porcelana são exclusivamente Particulares.",
        common_procedures: "Limpeza (Profilaxia), Clareamento Dental, Restauração, Tratamento de Canal (Endodontia), Implantes, Aparelho (Invisilign ou Fixo), Lentes de Contato em Porcelana, Extração do Siso.",
        consultation_duration: "Varia de 30 minutos a 2h por procedimento",
        pre_consultation_prep: "Nenhum preparo especial fora higiene bucal padrão.",
    },
    endocrinologia: {
        restrictions: "Não somos nutricionistas (embora haja orientações dietéticas focadas) e não vendemos dietas da moda.",
        differentials: "Tratamento baseado em ciência médica e evidências claras para emagrecimento ou distúrbios hormonais.",
        emergency_rules: "Hipoglicemia ou Hiperglicemia extrema em diabéticos (Confusão mental grave, hálito cetônico forte): levar para a emergência IMEDIATA.",
        return_policy: "Retorno tradicional em 15 a 30 dias para checar resultados de exames.",
        insurance_policy: "Emitimos laudo de reembolso para os demais.",
        common_procedures: "Diagnóstico e manejo de Diabetes, Tratamento de Obesidade, Doenças da Tireoide, Distúrbios hormonais masculinos/femininos, Terapia de reposição hormonal.",
        consultation_duration: "40-60 minutos",
        pre_consultation_prep: "Traga sempre os últimos exames de sangue recentes de fígado, tireoide, insulina/glicose, caso possua.",
    },
    otorrino: {
        restrictions: "Não realizamos grandes cirurgias cervicais profundas. Cirurgias de cabeça e pescoço oncológicas maiores são encaminhadas.",
        differentials: "Endoscopia nasal e exames na própria clínica, diagnóstico integrado.",
        emergency_rules: "Falta de ar mecânica impeditiva (engasgo obstruindo respiração), sangramento nasal que NÃO para com a pressão local por > 20 min: PS.",
        return_policy: "Retorno em 15 dias.",
        insurance_policy: "Exames acessórios as vezes requerem autorização prévia por parte dos convênios.",
        common_procedures: "Avaliação de Rinite/Sinusite, Remoção de cera, Exame Pró-labirintite (VENG), Audiometria, Laringoscopia, Indicação de Remoção de Amígdalas.",
        consultation_duration: "20-30 minutos",
        pre_consultation_prep: "Trazer exames de audição anteriores se tiver.",
    },
    urologia: {
        restrictions: "Não realizamos cirurgias oncológicas extensas fora do ambiente hospitalar e não realizamos inseminação artificial na clínica.",
        differentials: "Ambiente reservado e muito discreto, respeito total ao paciente. Urgência de pedras nos rins tratadas rapidamente.",
        emergency_rules: "Dor de cólica renal ALUCINANTE incontrolável com fortes vômitos, ou retenção urinária completa: encaminhar direto pro PS.",
        return_policy: "Retorno em 15 dias com os resultados de ultrassom/sangue.",
        insurance_policy: "Procedimentos cirúrgicos como vasectomia ou cirurgia a laser requerem internação por convênio.",
        common_procedures: "Checupe da Próstata (Toque e PSA), Manejo de Pedras nos Rins (Cálculo Renal), Disfunção erétil, Vasectomia, Infeccções urinárias recorrentes.",
        consultation_duration: "20-40 minutos",
        pre_consultation_prep: "Vir com bexiga cheia caso sua consulta possua teste de fluxo (fluxometria) ou ultrassom agendado em anexo.",
    },
    gastroenterologia: {
        restrictions: "Não fazemos cirurgias bariátricas ou de vesícula clínica (somente em hospital com nossa equipe). Endoscopias/Colonoscopias em estrutura própria ou de parceiros.",
        differentials: "Abordagem integral da saúde digestiva e conforto nas endoscopias sob sedação excelente.",
        emergency_rules: "Vômitos com sangue ou fezes intensamente pretas ou com sangue vivo abundante acompanhados de tontura: URGÊNCIA (PS IMEDIATO).",
        return_policy: "15-30 dias dependendo do prazo focado pelo médico para as biópsias da endoscopia saírem.",
        insurance_policy: "Muitos convênios pedem liberação formal das senhas para a Endoscopia/Colono antes e demoram de 3 a 5 dias.",
        common_procedures: "Tratamento Esofagite/Refluxo, Gastrite crônica, tratamento de H. Pylori, Síndrome do Intestino Irritável. (Muitas clínicas contam com a sala de Endoscopia).",
        consultation_duration: "30-40 minutos",
        pre_consultation_prep: "Para consulta simples não exige jejum (a não ser que vá no mesmo ato colher exames, endos/colono etc que exigem protocolo estrito).",
    },
    nutricao_fisio: {
        restrictions: "Nutricionistas e Fisioterapeutas NÃO prescrevem medicamentos (antibióticos, antidepressivos, anabolizantes), por lei. Só recomendamos fitoterápicos e suplementos se houver a permissão.",
        differentials: "Muito tempo dedicado, ferramentas visuais modernas para o corpo humano (bioimpedância, etc), foco preventivo enorme.",
        emergency_rules: "Sem grandes restrições de emergência crítica ligadas exclusivamnete.",
        return_policy: "Geralmente trabalhado no formato de Sessões ou Retornos agendados (exibição de dietas ou avanço funcional crônico).",
        insurance_policy: "Maioria particular, pacientes pedem laudo/relatório para reembolso corporativo.",
        common_procedures: "Nutrição: Planejamento Alimentar (Dieta), Exame de Bioimpedância Corporal, Nutrição Esportiva. Fisio: Reabilitação traumática/orto, RPG, Pilates Clínico, Fisioterapia Pélvica, Osteopatia.",
        consultation_duration: "50 min a 1 hora e meia (1ª consulta)",
        pre_consultation_prep: "Nutri: se houver bioimpedância, é orientada restrição de cafeína e hidratação regrada prévia. Fisio: traga roupas confortáveis ou de esporte.",
    },
    outros: {
        restrictions: "Consulte nossos atendentes se quiser garantir uma atividade que pareça controversa.",
        differentials: "Oferecemos o melhor serviço de atendimento médico disponível na região e acolhemos você.",
        emergency_rules: "Se sentir que corre risco de vida (fortes dores no peito, falta de ar severa ou paralisia): Dirija-se imediatamente a uma UPA ou Pronto-Socorro 24 horas, e ligue para o SAMU 192.",
        return_policy: "Válido dentro de 15 a 30 dias mediante a necessidade do médico requisitar exames.",
        insurance_policy: "Sugerimos tirar dúvidas a respeito da sua categoria específica nos passando seu cartão do plano.",
        common_procedures: "Consultas clínicas completas, avaliação de necessidades específicas e requisições de exames de rotina ou específicos.",
        consultation_duration: "Aproximadamente 30 minutos a 1 hora",
        pre_consultation_prep: "Traga CPF, CNH ou RG, carteira do seu plano de saúde válido e todos os exames médicos antigos e listas de remédios relevantes.",
    },
};

export function getSpecialtyTemplate(id: string): SpecialtyTemplate {
    return SPECIALTY_TEMPLATES[id] || SPECIALTY_TEMPLATES["outros"];
}
